name: Update Crypto Data Table

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual triggering

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04  # Specify a stable Ubuntu version

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install Dependencies
      run: |
        pip install gspread oauth2client pandas

    - name: Decode Service Account Credentials
      run: |
        echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" | base64 --decode > service_account.json

    - name: Fetch Data and Generate HTML
      env:
        SERVICE_ACCOUNT_FILE: 'service_account.json'
        SPREADSHEET_NAME: ${{ secrets.SPREADSHEET_NAME }}
        WORKSHEET_NAME: ${{ secrets.WORKSHEET_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python generate_crypto_table.py

    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add crypto_table.html
        git diff --cached --quiet || git commit -m "Automated update of crypto table at $(date)"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
